### ISSUE TITLE
Eating items on ground

### ISSUE THREAD

**Issue by freddydumont** [bears-team-3/roguelike#29]
When we walk over an item we are notified like so:
![corpse-on-ground](https://user-images.githubusercontent.com/15388588/29752846-73f93e48-8b33-11e7-992d-b385b795d9ea.png)

When pressing 'e' for eat, this happens, even when standing over an edible:
![nothing-to-eat](https://user-images.githubusercontent.com/15388588/29752850-8cb33da8-8b33-11e7-9f69-b4e362ad5512.png)

A nicer approach would be to allow the player to eat directly from the ground by showing the eat screen with a suffix for edibles on the ground:
![eatfromground](https://user-images.githubusercontent.com/15388588/29752863-bbcd49bc-8b33-11e7-9c59-cb44336020f9.jpg)

**Comment by ghost** [comment]
Currently, we have it so we need to loot the corpse then open the eat-menu to eat it. The current way allows the player to carry their food with them as they might not want to eat the food immediately. If we have it done the proposed way, the user will either have to eat the corpse immediately, or just move on with the level and ignore the corpse.
